# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10b5684c65b54b8530533d3e9c95e2b087d084a421037a9e3e84a18a236be9aeb77ca1270cac23f0ae8c237d9ff696ea850673c978f84d111a11f6fd970386b5

test:
  secret_key_base: 4cdf622e47971c1687bacf204a14f983efc0310d83d979dfcef06a3211bfa3c14b409f36e413b1601a3f36e3415a2f8303c112dec2a65e9380af4efbfb9a79e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
